name: flower-testbed

services:
  flower-testbed:
    image: phrp720/flower-testbed:latest
    container_name: flower-testbed
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL : "postgresql://floweruser:flowerpass@postgres:5432/flowertestbed?schema=public"
      NEXTAUTH_URL : http://0.0.0.0:3000
      NEXTAUTH_SECRET : q4FbKOLrloRaGo0AL4Xe34Xyb590wVVBi5WOUxFCU28=
      AUTH_USERNAME : admin
      AUTH_PASSWORD : admin
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15
    container_name: flower-testbed-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: floweruser
      POSTGRES_PASSWORD: flowerpass
      POSTGRES_DB: flowertestbed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U floweruser -d flowertestbed"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: