name: Release

on:
  release:
    types: [created]

jobs:
  package-release:
    name: Package Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package Production deployment
        run: |
          mkdir -p ./release/deployment  
          mkdir -p ./release/deployment/scripts
          cp -r ./scripts/schema ./release/deployment/scripts/
          cp -r ./deployments/production/* ./release/deployment/
          cp -r ./deployments/production/.* ./release/deployment/

      - name: Create ZIP file
        run: |
          cd release
          zip -r deployment.zip deployment

      - name: Upload artifacts
        run: |
          gh release upload ${{ github.event.release.tag_name }} release/deployment.zip
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        shell: bash